### ISSUE TITLE
Transfer over `comb` package on crates.io

### ISSUE THREAD

**Issue by hwittenborn** [museun/comb#2]
Hi! I have a [project](https://github.com/hwittenborn/comb) that's also called `comb`, and I was wondering if you'd be fine with transferring the name over. I only ask because it appears this project has been inactive as of the last couple of years, and it didn't look like this crate was needed by any other package on crates.io.

Just asking out of curiosity, let me know if you'd be down with it! :)

**Comment by museun** [comment]
Sure, I'll add you as an owner. You can then remove me and push a yank release or whatever you want to 'fix' the semver.

**Comment by hwittenborn** [comment]
Thanks, appreciate it a ton!

**Comment by museun** [comment]
Its not a problem, I had honestly forgotten about this project. I do wish crates.io had namespacing so this would never be an issue, but alas mistakes in history.

**Comment by hwittenborn** [comment]
> I do wish crates.io had namespacing so this would never be an issue

Fully agreed, that kind of functionality would definitely be nice. I saw a post on it on the Rust internals forum, looks like it didn't really get anywhere. 100% would be nice though
